MAIN_FONT = "Bahnschrift"
FONT_SIZE = 12

BACKGROUND_COLOR = "#FFFFFF"
TEXT_COLOR = "#31333F"

BORDER_RADIUS = 5
EDGE_WIDTH_BORDER = 1
COLOR_BORDER = "#FF4B4B"

PADDING = 5

HOVER_COLOR = "#ce3d3d"
BACKGROUND_TEXT_EDIT_COLOR = "#ededed"
DISABLE_COLOR = ""

HEIGHT_SPINBOX = 24
HEIGHT_LINEEDIT = 22
HEIGHT_PUSHBUTTON = 20
