MAIN_FONT = "Bahnschrift"
FONT_SIZE = 12

BACKGROUND_COLOR = "#FFFFFF"
TEXT_COLOR = "#31333F"

BORDER_RADIUS = 5
BORDER_WIDTH_EDGE = 1
BORDER_COLOR = "#FF4B4B"

PADDING = 5

HOVER_COLOR = "#ce3d3d"
DISABLE_COLOR = ""

LOGGER_BACKGROUND_COLOR = "#ededed"

SPINBOX_HEIGHT = 24
LINEEDIT_HEIGHT = 22
PUSHBUTTON_HEIGHT = 20

INFOBOX_MIN_WIDTH = 200
INFOBOX_MAX_WIDTH = 300
INFOBOX_SHADE_COLOR = '#000000'
INFOBOX_BG_COLOR = "#FFFFFF"
INFOBOX_BORDER_COLOR = '#000000'